AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This serverless application publishes AWS Route 53 events to NS1 Connect.
Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: true
Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-route53-ns1-connect
    Description: This serverless application publishes AWS Route 53 events to NS1
      Connect.
    Author: NS1
    SpdxLicenseId: Apache-2.0
    LicenseUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-5bpg79c8x6lw/86d3f3a95c324c9479bd8986968f4327
    ReadmeUrl: s3://aws-sam-cli-managed-default-samclisourcebucket-5bpg79c8x6lw/16efd6fc765d483c4867e59be0268e3b
    Labels:
    - serverless
    - NS1
    - Route53
    - DNS
    HomePageUrl: https://github.com/ns1/cloudsync
    SemanticVersion: '0.3.1'
    SourceCodeUrl: https://github.com/ns1/cloudsync/tree/0.3.1
Parameters:
  CloudTrailBucketName:
    Type: String
    Default: cloud-sync-trail-bucket
  CloudTrailName:
    Type: String
    Default: CloudSyncTrail
  SecretName:
    Type: String
    Default: CloudSync/APIKey
  NS1APIKey:
    Type: String
    Default: api_key
Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Metadata:
      SamResourceId: DeadLetterQueue
  TrailKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Enabled: true
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      PendingWindowInDays: 7
      KeyPolicy:
        Version: '2012-10-17'
        Id: default-key-policy
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Action:
          - kms:*
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
          Resource: '*'
        - Sid: Allow CloudTrail to encrypt logs
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action:
          - kms:GenerateDataKey*
          Resource: '*'
          Condition:
            StringEquals:
              AWS:SourceArn:
                Fn::Sub: arn:aws:cloudtrail:us-east-1:${AWS::AccountId}:trail/${CloudTrailName}
            StringLike:
              kms:EncryptionContext:aws:cloudtrail:arn:
                Fn::Sub: arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*
        - Sid: Allow CloudTrail to describe key
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action:
          - kms:DescribeKey
          Resource: '*'
        - Sid: Allow principals in the account to decrypt log files
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - kms:Decrypt
          - kms:ReEncryptFrom
          Resource: '*'
          Condition:
            StringEquals:
              kms:CallerAccount:
                Fn::Sub: ${AWS::AccountId}
            StringLike:
              kms:EncryptionContext:aws:cloudtrail:arn:
                Fn::Sub: arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*
        - Sid: Allow alias creation during setup
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - kms:CreateAlias
          Resource: '*'
          Condition:
            StringEquals:
              kms:CallerAccount:
                Fn::Sub: ${AWS::AccountId}
              kms:ViaService: ec2.us-east-1.amazonaws.com
        - Sid: Enable cross account log decryption
          Effect: Allow
          Principal:
            AWS: '*'
          Action:
          - kms:Decrypt
          - kms:ReEncryptFrom
          Resource: '*'
          Condition:
            StringEquals:
              kms:CallerAccount:
                Fn::Sub: ${AWS::AccountId}
            StringLike:
              kms:EncryptionContext:aws:cloudtrail:arn:
                Fn::Sub: arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*
    Metadata:
      SamResourceId: TrailKMSKey
  TrailS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName:
        Ref: CloudTrailBucketName
    Metadata:
      SamResourceId: TrailS3Bucket
  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: TrailS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: Check ACLs
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:GetBucketAcl
          Resource:
            Fn::GetAtt:
            - TrailS3Bucket
            - Arn
          Condition:
            StringEquals:
              aws:SourceArn:
                Fn::Sub: arn:aws:cloudtrail:us-east-1:${AWS::AccountId}:trail/${CloudTrailName}
        - Sid: Write Access
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:PutObject
          Resource:
            Fn::Sub: arn:aws:s3:::${CloudTrailBucketName}/AWSLogs/${AWS::AccountId}/*
          Condition:
            StringEquals:
              s3:x-amz-acl: bucket-owner-full-control
    Metadata:
      SamResourceId: TrailBucketPolicy
  Trail:
    Type: AWS::CloudTrail::Trail
    DependsOn: TrailBucketPolicy
    Properties:
      S3BucketName:
        Ref: CloudTrailBucketName
      IsLogging: true
      TrailName:
        Ref: CloudTrailName
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      KMSKeyId:
        Fn::GetAtt:
        - TrailKMSKey
        - Arn
    Metadata:
      SamResourceId: Trail
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        account:
        - Fn::Sub: ${AWS::AccountId}
        source:
        - aws.route53
        detail:
          eventSource:
          - route53.amazonaws.com
          eventName:
          - CreateHostedZone
          - DeleteHostedZone
          - UpdateHostedZoneComment
          - ChangeResourceRecordSets
          errorCode:
          - exists: false
      Targets:
      - Arn:
          Fn::GetAtt:
          - DNSUpdateFunction
          - Arn
        Id: DNSUpdateFunction
        DeadLetterConfig:
          Arn:
            Fn::GetAtt:
            - DeadLetterQueue
            - Arn
        RetryPolicy:
          MaximumRetryAttempts: 4
    Metadata:
      SamResourceId: EventRule
  EventBridgeToToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: DeadLetterQueue
      PolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: events.amazonaws.com
          Action:
          - SQS:SendMessage
          Resource:
            Fn::GetAtt:
            - DeadLetterQueue
            - Arn
    Metadata:
      SamResourceId: EventBridgeToToSqsPolicy
  IAMRoleForLambdaFunctionRoute53:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: CloudSyncLambdaExecRole
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - secretsmanager:GetSecretValue
            Resource: '*'
            Condition:
              StringEquals:
                secretsmanager:ResourceTag/APIKey: NS1
          - Effect: Allow
            Action:
            - sqs:SendMessage
            - sqs:GetQueueAttributes
            Resource:
              Fn::GetAtt:
              - DeadLetterQueue
              - Arn
    Metadata:
      SamResourceId: IAMRoleForLambdaFunctionRoute53
  DNSUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-5bpg79c8x6lw/d2b2defc0902e48411a075b6d7b9a20e
      Handler: app.handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Timeout: 10
      Role:
        Fn::GetAtt:
        - IAMRoleForLambdaFunctionRoute53
        - Arn
      Environment:
        Variables:
          ENDPOINT: https://e9y7a31hjf.execute-api.us-east-1.amazonaws.com/Prod
          SECRET_NAME:
            Ref: SecretName
          ACCOUNT_ID:
            Ref: AWS::AccountId
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
      EventInvokeConfig:
        MaximumRetryAttempts: 2
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
    Metadata:
      SamResourceId: DNSUpdateFunction
  RoleForConfigureFunction:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: CloudSyncConfigFunctionRole
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - secretsmanager:CreateSecret
            - secretsmanager:DeleteSecret
            - secretsmanager:TagResource
            Resource: '*'
          - Effect: Allow
            Action:
            - s3:ListObjects
            - s3:DeleteObject
            Resource:
              Fn::GetAtt:
              - TrailS3Bucket
              - Arn
    Metadata:
      SamResourceId: RoleForConfigureFunction
  ConfigureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-5bpg79c8x6lw/8217e0f5beeca41ef56c62336ec70c47
      Handler: app.configure_application
      Runtime: python3.9
      Timeout: 15
      Architectures:
      - x86_64
      Role:
        Fn::GetAtt:
        - RoleForConfigureFunction
        - Arn
      Environment:
        Variables:
          SECRET_NAME:
            Ref: SecretName
          API_KEY:
            Ref: NS1APIKey
          LOCK_BUCKET_NAME: SnapshotBucket
    Metadata:
      SamResourceId: ConfigureFunction
  ConfigureCustomResource:
    Type: Custom::ConfigureFunction
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - ConfigureFunction
        - Arn
      CloudTrailBucketName:
        Ref: CloudTrailBucketName
    Metadata:
      SamResourceId: ConfigureCustomResource
