AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This serverless application publishes AWS Route 53 events to NS1 Connect.

Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: True

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-route53-ns1-connect
    Description: This serverless application publishes AWS Route 53 events to NS1 Connect.
    Author: NS1
    SpdxLicenseId: Apache-2.0
    # paths are relative to .aws-sam/build directory
    LicenseUrl: ../../LICENSE
    ReadmeUrl: ./README.md
    Labels: [serverless, NS1, Route53, DNS]
    HomePageUrl: https://github.com/ns1/cloudsync
    SemanticVersion: 0.3.2
    SourceCodeUrl: https://github.com/ns1/cloudsync/tree/0.3.2

Parameters:
  CloudTrailBucketName:
    Type: String
    Default: cloud-sync-trail-bucket
  CloudTrailName:
    Type: String
    Default: CloudSyncTrail
  SecretName:
    Type: String
    Default: CloudSync/APIKey
  NS1APIKey:
    Type: String
    Default: api_key

Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue

  # KMS key for CloudTrail S3 bucket.
  TrailKMSKey:
    Type: AWS::KMS::Key
    Properties: 
      Enabled: true
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      PendingWindowInDays: 7
      KeyPolicy:
        Version: '2012-10-17'
        Id: default-key-policy
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Action: 
              - kms:*
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Resource: "*"
          - Sid: "Allow CloudTrail to encrypt logs"
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 
              - kms:GenerateDataKey*
            Resource: "*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudtrail:us-east-1:${AWS::AccountId}:trail/${CloudTrailName}
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*
          - Sid: "Allow CloudTrail to describe key"
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: 
              - kms:DescribeKey
            Resource: "*"
          - Sid: "Allow principals in the account to decrypt log files"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Decrypt
              - kms:ReEncryptFrom
            Resource: "*"
            Condition:
              StringEquals:
                kms:CallerAccount: !Sub ${AWS::AccountId}
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*
          - Sid: "Allow alias creation during setup"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:CreateAlias
            Resource: "*"
            Condition:
              StringEquals:
                kms:CallerAccount: !Sub ${AWS::AccountId}
                kms:ViaService: ec2.us-east-1.amazonaws.com
          - Sid: "Enable cross account log decryption"
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Decrypt
              - kms:ReEncryptFrom
            Resource: "*"
            Condition:
              StringEquals:
                kms:CallerAccount: !Sub ${AWS::AccountId}
              StringLike:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:*:${AWS::AccountId}:trail/*

  # S3 bucket for CloudTrail.
  TrailS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref CloudTrailBucketName

  # Bucket policy to allow CloudTrail access to the bucket.
  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrailS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: Check ACLs
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt TrailS3Bucket.Arn
            Condition:
              StringEquals:
                aws:SourceArn: !Sub arn:aws:cloudtrail:us-east-1:${AWS::AccountId}:trail/${CloudTrailName}
          - Sid: Write Access
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${CloudTrailBucketName}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  # There must be a trail in order for EventBridge to capture events from Route 53.
  Trail:
    Type: AWS::CloudTrail::Trail
    DependsOn: TrailBucketPolicy
    Properties:
      S3BucketName: !Ref CloudTrailBucketName
      IsLogging: true
      TrailName: !Ref CloudTrailName
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      KMSKeyId: !GetAtt TrailKMSKey.Arn

  # An EventBridge rule that queues all Route 53 updates from CloudTrail.
  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      EventPattern: 
        account: 
          - !Sub '${AWS::AccountId}'
        source:
          - aws.route53
        detail:
          eventSource:
            - route53.amazonaws.com
          eventName:
            - CreateHostedZone
            - DeleteHostedZone
            - UpdateHostedZoneComment
            - ChangeResourceRecordSets
          errorCode:
            - exists: false
      Targets: 
        - Arn: !GetAtt DNSUpdateFunction.Arn
          Id: "DNSUpdateFunction"
          DeadLetterConfig:
            Arn: !GetAtt DeadLetterQueue.Arn
          RetryPolicy:
            MaximumRetryAttempts: 4


  # A policy that allows the EventBridge rule to send messages to the dead-letter queue.
  EventBridgeToDLQPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: DeadLetterQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 
              - SQS:SendMessage
            Resource:  !GetAtt DeadLetterQueue.Arn

  IAMRoleForLambdaFunctionRoute53:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CloudSyncLambdaExecRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"
                Condition:
                  StringEquals:
                    secretsmanager:ResourceTag/APIKey: "NS1"
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt DeadLetterQueue.Arn
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Ref DNSUpdateFunction
                Principal:
                  Service: events.amazonaws.com
                Condition:
                  ArnLike:
                    AWS:SourceArn: !GetAtt EventRule.Arn

  # A Lambda residing in this account that receives updates from Route 53 via CloudTrail.
  DNSUpdateFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./src/dns_updates
        Handler: app.handler
        Runtime: python3.9
        Architectures:
          - x86_64
        Timeout: 10
        Role: !GetAtt IAMRoleForLambdaFunctionRoute53.Arn
        Environment:
          Variables:
            # ENDPOINT: https://api.cloudsyncv2.nsone.co/dns
            ENDPOINT: https://e9y7a31hjf.execute-api.us-east-1.amazonaws.com/Prod
            SECRET_NAME: !Ref SecretName
            ACCOUNT_ID: !Ref AWS::AccountId
        Layers:
          - !Sub arn:aws:lambda:${AWS::Region}:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
        EventInvokeConfig:
          MaximumRetryAttempts: 2
        DeadLetterQueue:
          Type: SQS
          TargetArn: !GetAtt DeadLetterQueue.Arn 

  RoleForConfigureFunction:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CloudSyncConfigFunctionRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:CreateSecret
                  - secretsmanager:DeleteSecret
                  - secretsmanager:TagResource
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:ListObjects
                  - s3:DeleteObject
                Resource: !GetAtt TrailS3Bucket.Arn
 
  ConfigureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/configure
      Handler: app.configure_application
      Runtime: python3.9
      Timeout: 15
      Architectures:
        - x86_64
      Role: !GetAtt RoleForConfigureFunction.Arn
      Environment:
        Variables:
          SECRET_NAME: !Ref SecretName
          API_KEY: !Ref NS1APIKey
          LOCK_BUCKET_NAME: SnapshotBucket
  
  ConfigureCustomResource:
    Type: Custom::ConfigureFunction
    Properties:
      ServiceToken: !GetAtt ConfigureFunction.Arn
      CloudTrailBucketName: !Ref CloudTrailBucketName 
  
  # SnapshotFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: ./src/dns_snapshot
  #     Handler: app.lambda_handler
  #     Runtime: python3.9
  #     Architectures:
  #       - x86_64
  
  # SnapshotSNSPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: !Ref SnapshotFunction
  #     Principal: sns.amazonaws.com
  
  # SnapshotTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     Subscription:
  #       - Protocol: lambda
  #         Endpoint: !GetAtt SnapshotFunction.Arn
  
  # SnapshotCustomResource:
  #   Type: AWS::CloudFormation::CustomResource
  #   Properties:
  #     ServiceToken: !GetAtt SnapshotTopic.TopicArn
