AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This serverless application publishes AWS Route 53 events to NS1 Connect.

Globals:
  Function:
    Timeout: 10
    Tracing: Active
  Api:
    TracingEnabled: True

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-route53-ns1-connect
    Description: This serverless application publishes AWS Route 53 events to NS1 Connect.
    Author: NS1
    SpdxLicenseId: Apache-2.0
    # paths are relative to .aws-sam/build directory
    LicenseUrl: ../../LICENSE
    ReadmeUrl: ../../README.md
    Labels: [serverless, NS1, Route53]
    HomePageUrl: https://github.com/ns1/cloudsync
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/ns1/cloudsync/tree/1.0.0

Parameters:
  NS1APIKey:
    Type: String
    Default: ir77L4cYvsTVgKP0JWr6

Resources:

  # A queue to hold Route 53 updates for this account.
  DNSUpdateQueue:
    Type: AWS::SQS::Queue

  # AlarmTopic:
  #   Type: AWS::SNS::Topic

  # QueueDepthAlarm:
  #   Type: AWS::CloudWatch::Alarm
  #   Properties:
  #     AlarmDescription: "Alarm if queue grows too large"
  #     Namespace: "AWS/SQS"
  #     MetricName: ApproximateNumberOfMessagesVisible
  #     Dimensions:
  #       - Name: QueueName
  #         Value: !GetAtt DNSUpdateQueue.QueueName
  #     Statistic: Sum
  #     Period: 300
  #     EvaluationPeriods: 1
  #     Threshold: 10
  #     ComparisonOperator: GreaterThanThreshold
  #     AlarmActions:
  #       - Ref: AlarmTopic
  #     InsufficientDataActions:
  #       - Ref: AlarmTopic

  # An EventBridge rule that queues all Route 53 updates from CloudTrail.
  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      EventPattern: 
        account: 
          - !Sub '${AWS::AccountId}'
        source:
          - aws.route53
        detail:
          eventSource:
            - route53.amazonaws.com
          eventName:
            - CreateHostedZone
            - DeleteHostedZone
            - UpdateHostedZoneComment
            - ChangeResourceRecordSets
          errorCode:
            - exists: false
      Targets: 
        - Arn: !GetAtt DNSUpdateQueue.Arn
          Id: "SQSqueue"

  # A policy that allows the EventBridge rule to send messages to the queue.
  EventBridgeToToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: DNSUpdateQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 
              - SQS:SendMessage
            Resource:  !GetAtt DNSUpdateQueue.Arn
  
  # A queue policy that allows a Lambda function residing in an NS1-controlled
  # AWS account to read and delete messages from the queue.
  NS1LambdaSqsAccessPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: DNSUpdateQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                - arn:aws:iam::249121138663:role/CloudSyncLambdaExecutionRole
            Action: 
              - SQS:ReceiveMessage
              - SQS:DeleteMessage
            Resource:  !GetAtt DNSUpdateQueue.Arn

  IAMRoleForLambdaFunctionRoute53:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CloudSyncLambdaExecRole
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "*"
                Condition:
                  StringEquals:
                    secretsmanager:ResourceTag/APIKey: "NS1"
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt DNSUpdateQueue.Arn

  # A Lambda residing in this account that receives updates
  # from Route 53 via an SQS queue.
  Route53toNS1Connect:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ./src/dns_updates
        Handler: app.handler
        Runtime: python3.9
        Architectures:
          - x86_64
        Timeout: 10
        Role: !GetAtt IAMRoleForLambdaFunctionRoute53.Arn
        Environment:
          Variables:
            ENDPOINT: https://api.cloudsyncv2.nsone.co/dns
            # NS1APIKEY: ir77L4cYvsTVgKP0JWr6
        Layers:
          - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:4
        Events:
          SQSEvent:
            Type: SQS
            Properties:
              Queue: !GetAtt DNSUpdateQueue.Arn
              BatchSize: 10
              FunctionResponseTypes:
                - ReportBatchItemFailures
              MaximumBatchingWindowInSeconds: 1
        # Policies:
        #   - Version: '2012-10-17'
        #     Statement:
        #       - Effect: Allow
        #         Action:
        #           - route53:ListResourceRecordSets
        #         Resource: arn:aws:route53:::hostedzone/*
  
  # SnapshotFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: ./src/dns_snapshot
  #     Handler: app.lambda_handler
  #     Runtime: python3.9
  #     Architectures:
  #       - x86_64
  
  # SnapshotSNSPermission:
  #   Type: AWS::Lambda::Permission
  #   Properties:
  #     Action: lambda:InvokeFunction
  #     FunctionName: !Ref SnapshotFunction
  #     Principal: sns.amazonaws.com
  
  # SnapshotTopic:
  #   Type: AWS::SNS::Topic
  #   Properties:
  #     Subscription:
  #       - Protocol: lambda
  #         Endpoint: !GetAtt SnapshotFunction.Arn
  
  # SnapshotCustomResource:
  #   Type: AWS::CloudFormation::CustomResource
  #   Properties:
  #     ServiceToken: !GetAtt SnapshotTopic.TopicArn
