AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaDeadLetterQueue: 
    Type: AWS::SQS::Queue

  IAMRoleForLambdaFunctionRoute53:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: Route53
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - route53:ListResourceRecordSets
                Resource: arn:aws:route53:::hostedzone/*
        - PolicyName: SQSDeadLetter
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt LambdaDeadLetterQueue.Arn

  LambdaFunctionRequestsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.9
      Content:
        S3Bucket: cloudsync-v2-lambda
        S3Key: layer.zip
  
  LambdaFunctionRoute53:
    Type: AWS::Lambda::Function
    Properties:
      Handler: aws.lambda.app.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Role: !GetAtt IAMRoleForLambdaFunctionRoute53.Arn
      Layers:
        - !Ref LambdaFunctionRequestsLayer
      DeadLetterConfig:
        TargetArn: !GetAtt LambdaDeadLetterQueue.Arn
      Environment:
        Variables:
          ENDPOINT: https://333b-68-161-187-233.ngrok.io
      Code:
        S3Bucket: cloudsync-v2-lambda
        S3Key: cloudsync-lambda.zip

  EventBridgeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunctionRoute53.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt r53EventRule.Arn
  
  r53EventRule:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Description: Notify on R53 changes
      EventBusName: default
      State: ENABLED
      Name: r53CloudSyncEventRule
      EventPattern:
        source:
          - aws.route53
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventSource:
            - route53.amazonaws.com
          eventName:
            - CreateHostedZone
            - DeleteHostedZone
            - UpdateHostedZoneComment
            - ChangeResourceRecordSets
      Targets: 
        - Arn: !GetAtt 
            - LambdaFunctionRoute53
            - Arn
          Id: r53CloudSyncNotificationsLambda
