name: Push AWS Lambda to S3

on: 
  release:
    types: [published]

jobs:
  upload-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Make artifact directory
        run: mkdir ./artifacts

      - name: Create Zip File
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r ./artifacts/cloudsync-lambda.zip ./aws/lambda/

      - name: Push Zip to S3
        uses: jakejarvis/s3-sync-action@v0.3.1
        env:
          SOURCE_DIR: './artifacts'
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: 'cloudsync-v2-lambda'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
